FROM node:18-alpine
WORKDIR /app
COPY package*.json .
RUN npm install  --production

COPY . .
EXPOSE 80

RUN addgroup -s appgroup && adduser -S appuser  -G appgroup
USER appuser

CMD [ "node","server.js" ]
